# Generated by Django 4.2 on 2024-06-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
